### ISSUE TITLE
S-C ver.2017-04-05 crashes while S-C ver.2016-07-30 *WORKS WELL*

### ISSUE THREAD

**Issue by Bab64** [jbeard4/SCION-CORE#47]
Hi. In attempting  to upgrade SCION-CORE, my app no longer works... The problem occurs when sending a given event, i.e., 'sm.gen(x);'. Note: all event sendings work well except this one!
The reception has a condition which properly executes and return 'true' as expected but the transition fails (this however *WORKS WELL* with ver.2016-07-30).
By catching the exception at sending time, here is the error content (please note that I use the Three.js 3D lib.). Again, this execpetion *DOES NOT OCCUR* with ver.2016-07-30!

Any help welcome! Regards.

TypeError: Cannot read property '860A9EED-0AD3-4581-9BA7-04C70E30E502' of undefined
    at qd.toJSON (http://localhost:8383/NoLanguage/js/three.js/three.min.js:291:383)
    at Ja.toJSON (http://localhost:8383/NoLanguage/js/three.js/three.min.js:437:182)
    at JSON.stringify (<anonymous>)
    at p._performSmallStep (http://localhost:8383/NoLanguage/js/SCION-CORE/scion.min2017.js:2:11693)
    at p._performBigStep (http://localhost:8383/NoLanguage/js/SCION-CORE/scion.min2017.js:2:10830)
    at p.gen (http://localhost:8383/NoLanguage/js/SCION-CORE/scion.min2017.js:2:18311)
    at NoLanguagePlayground.<anonymous> (http://localhost:8383/NoLanguage/js/NoLanguagePlayground.js:563:137)
    at p._evaluateAction (http://localhost:8383/NoLanguage/js/SCION-CORE/scion.min2017.js:2:13412)
    at p._performSmallStep (http://localhost:8383/NoLanguage/js/SCION-CORE/scion.min2017.js:2:12778)
    at p._performBigStep (http://localhost:8383/NoLanguage/js/SCION-CORE/scion.min2017.js:2:10830)

**Comment by jbeard4** [comment]
Can you dump the 2016 and 2017 versions of the object that is being passed to JSON.stringify during the failing small step? Thanks.

**Comment by Bab64** [comment]
I got more precise details. My code sends an event with a **x** parameter as follows:

- sm.gen('event_name',x);

1. Removing **x** removes the bug! So **x** is the source of the problem...
2. I next tried this code:

- JSON.stringify(x); // Bug is here
- sm.gen('event_name',x);

The program then crashes at stringification time! Don't know to dump **x** then since stringification  is impossible?

Last point: in testing with older version (SC ver.2016-07-30), the stringification also fails (logical and expected). The question is then why SC ver.2016-07-30 and very last ver. of SC run stringifications in a different way? I don't have any latitude on the **x** property causing the problem since this property (apparently) comes from Three.js (see error log).

Go on and will post new data if progresses made...

**Comment by jbeard4** [comment]
Can you try to dump the object using json-stringify-safe? https://github.com/isaacs/json-stringify-safe

**Comment by jbeard4** [comment]
Would it be possible to break on error, and inspect the object that is undefined when JSON.stringify attempts to access property '860A9EED-0AD3-4581-9BA7-04C70E30E502'? What is this object that is defined in the 2016 version, and undefined in the 2017 version?

**Comment by Bab64** [comment]
New information:
- json-stringify-safe also fails (no actual help)
- the property name (see below) changes from one execution to another one. Apparently, Three.js manages the 'undefined' object owning this property. This object is embedded in mine, **x** above.
- the 'toJSON' function (lines 1 and 2 of error log) is not applied to the same fields from one execution to another: fields 'qd' and 'Ja' above and fields: 'oc' and 'Aa' below -> strange???


TypeError: Cannot read property '8BBDC24C-1128-4B39-AD65-52767A4590F9' of undefined
    at oc.toJSON (http://localhost:8383/NoLanguage/js/node_modules/three/build/three.min.js:295:499)
    at Aa.toJSON (http://localhost:8383/NoLanguage/js/node_modules/three/build/three.min.js:443:157)
    at JSON.stringify (<anonymous>)
    at p._performSmallStep (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.min.js:2:11676)
    at p._performBigStep (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.min.js:2:10813)
    at p.gen (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.min.js:2:18304)
    at NoLanguagePlayground.<anonymous> (http://localhost:8383/NoLanguage/js/source/NoLanguagePlayground.js:579:137)
    at p._evaluateAction (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.min.js:2:13395)
    at p._performSmallStep (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.min.js:2:12761)
    at p._performBigStep (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.min.js:2:10813)

**Comment by jbeard4** [comment]
Can you try the non-minified version of three.js so we can see a stack trace where method names are not mangled?
Can you also verify that the version of three.js is the same across your tests? It's strange that you got a different stack traces in different tests.

**Comment by jbeard4** [comment]
Please try the following build:
https://github.com/jbeard4/SCION-CORE/blob/fix-47/dist/scion.min.js

Thank you.

**Comment by jbeard4** [comment]
You can comment here: https://github.com/jbeard4/SCION-CORE/pull/48

**Comment by Bab64** [comment]
Retried tests with **non-minified** version of Three.js (see error log) and **SAME** ver. of Three.js (release 0.87). Again, the property name ('F99EF8A8-2FA7-4A6F-B909-FAB4EA412389'  in error log below) changes from one execution to another.
Important note: I was not able to use the very last build of SCION-CORE because of a parsing error at loading time! Well-formed build may solve the problem?

New data: it seems that 'F99EF8A8-2FA7-4A6F-B909-FAB4EA412389' is the value of a field named 'uuid' in CanvasTexture objects. It makes sense that this value changes from one execution to another since it is the randomized id. of a texture.
In my object, a CanvasTexture object is pointed **TWICE**. Is it the reason why the stringification of SCION-CORE fails???

TypeError: Cannot read property 'F99EF8A8-2FA7-4A6F-B909-FAB4EA412389' of undefined
    at CanvasTexture.toJSON (http://localhost:8383/NoLanguage/js/node_modules/three/build/three.js:1072:28)
    at MeshPhongMaterial.toJSON (http://localhost:8383/NoLanguage/js/node_modules/three/build/three.js:7340:62)
    at JSON.stringify (<anonymous>)
    at Statechart._performSmallStep (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.js:904:71)
    at Statechart._performBigStep (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.js:849:22)
    at Statechart.gen (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.js:1439:14)
    at NoLanguagePlayground.<anonymous> (http://localhost:8383/NoLanguage/js/source/NoLanguagePlayground.js:575:137)
    at Statechart._evaluateAction (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.js:1025:34)
    at Statechart._performSmallStep (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.js:981:34)
    at Statechart._performBigStep (http://localhost:8383/NoLanguage/js/node_modules/scion-core/dist/scion.js:849:22)

**Comment by Bab64** [comment]
**SOLVED**! I've downloaded the new build from the Web (instead of through e-mailer) and parsing error disappeared

https://github.com/jbeard4/SCION-CORE/blob/fix-47/dist/scion.min.js
